### ISSUE TITLE
bug(validation): validation exception status is overwritten

### ISSUE THREAD

**Issue by paul-thebaud** [laravel-json-api/exceptions#3]
When throwing a validation exception, like in the following code, the exception status (if specified) is overwritten to a 422 status code:

```php
use Illuminate\Validation\ValidationException;

throw ValidationException::withMessages([
    'data.email' => 'Too many attempts',
])->status(419);
```

I think this could be fixed inside the [`ValidationExceptionHandler` class](https://github.com/laravel-json-api/exceptions/blob/develop/src/Pipes/ValidationExceptionHandler.php#L54).

**Comment by paul-thebaud** [comment]
Looks like there is still problem with my PR: error status and title in response body are not infered from the exception status (status is still 422 and text still "Unprocessable Entity").

I don't know how to fix this without making a lot of changes, so I will let you do the work. I'll close my PR and wait for a fix.

**Comment by lindyhopchris** [comment]
Hi! Thanks for reporting. This is due to me not be aware that you could set a status on the validation exception. It definitely needs fixing so I'll take a look next time I'm on JSON:API things (will definitely be looking during the coming week).

**Comment by lindyhopchris** [comment]
@paul-thebaud actually had time to look at this tonight. can you give it a go before I tag? to bring in the fix:

```bash
composer require "laravel-json-api/exceptions:dev-hotfix/2.0.1 as v2.0.1"
```

If you're interested, this is how I've fixed it: https://github.com/laravel-json-api/exceptions/commit/501ff105ee073288b83ff2274c4bd73928e7fdec

**Comment by paul-thebaud** [comment]
Hi @lindyhopchris, thank you for the quick fix. Code looks good to me. I'll give a try to the update inside my app tomorrow 🙂

**Comment by paul-thebaud** [comment]
@lindyhopchris, looks good to me. Well done, thanks again :tada:

**Comment by lindyhopchris** [comment]
Great, thanks for confirming! I've tagged as `2.0.1`
